layout_spectrum: 0.6297669738996774
typography_spectrum: 0.784855336882174
color:
  brandStrength: 0.03812885982915759
  lightness: 0.45561818149872124
  saturation: 0.6981437846552581
  rhythmicContrast: 0.5061763266567141
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: FIRST SITE
