typography_spectrum: 0.784855336882174
color:
  brandStrength: 0.03812885982915759
  lightness: 0.45561818149872124
  saturation: 0.6981437846552581
  rhythmicContrast: 0.5061763266567141
  brandColors:
    - '#5C614B'
    - '#ACAAAD'
    - '#8B8B89'
    - '#322920'
    - '#CB3842'
layout_spectrum: 0.6297669738996774
name: FIRST SITE
title: GUITAR CHORDS
description: FIND YOUR JAM
